### ISSUE TITLE
リポジトリ名typoしてます

### ISSUE THREAD

**Issue by Ancient-Scapes** [LeeDDHH/gigazineDaily#1]
誤
- gigagineDaily

正
- gigazineDaily

だと思います！

**Comment by LeeDDHH** [comment]
typo気づかなかったです！
ありがとうございます！

**Comment by Ancient-Scapes** [comment]
おけまる 🚀

**Comment by LeeDDHH** [comment]
リポジトリ名変更
https://qiita.com/ntkgcj/items/e4dd5cb04ffd7063bc4e
